version: "3.9"
services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: 'feast_db'
      POSTGRES_USER: 'user'     #TODO change user and password before production
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
   # volumes:
   #   - './init:/docker-entrypoint-initdb.d'