version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=ogv/ogv27112002
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
