# to create container run 'docker-compose up -d' in this directory
version: "3.9"
services:
  polzunov-feast-db:
    container_name: polzunov-feast-db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: 'polzunov-feast-db'
      POSTGRES_USER: 'polzunov'
      POSTGRES_PASSWORD: 'feast'
    ports:
      - '5432:5432'
    volumes:
      - polzunov-feast-data:/var/lib/postgresql/data
volumes:
  polzunov-feast-data:
    name: polzunov-feast-data