root:
  #TODO substitute with env variables before prod
  username: root
  password: root123!

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polzunov-feast-db
    username: polzunov
    password: feast
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
