spring:
  messages:
    basename: ErrorResponseMessages,ValidationViolationMessages

  datasource:
    url: jdbc:postgresql://localhost:5432/feast_db
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
