root:
  email: root@root.root
  password: root123!

spring:
  datasource:
    url: jdbc:h2:mem:polzunov-feast-db
    username: polzunov
    password: feast
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
